
IF DB_ID('ExameDb') IS NULL
BEGIN
    CREATE DATABASE ExameDb;
END
GO

USE ExameDb;
GO

IF OBJECT_ID('MOVIMENTO_MANUAL', 'U') IS NOT NULL DROP TABLE MOVIMENTO_MANUAL;
IF OBJECT_ID('PRODUTO_COSIF', 'U') IS NOT NULL DROP TABLE PRODUTO_COSIF;
IF OBJECT_ID('PRODUTO', 'U') IS NOT NULL DROP TABLE PRODUTO;
GO

CREATE TABLE PRODUTO (
    COD_PRODUTO        VARCHAR(11)  NOT NULL PRIMARY KEY,
    DES_PRODUTO        VARCHAR(50)  NOT NULL,
    STA_STATUS         CHAR(1)      NOT NULL
);
GO

CREATE TABLE PRODUTO_COSIF (
    COD_PRODUTO        VARCHAR(11)  NOT NULL,
    COD_COSIF          VARCHAR(11)  NOT NULL,
    COD_CLASSIFICACAO  VARCHAR(6)   NOT NULL,
    STA_STATUS         CHAR(1)      NOT NULL,
    CONSTRAINT PK_PRODUTO_COSIF PRIMARY KEY (COD_PRODUTO, COD_COSIF),
    CONSTRAINT FK_PROD_COSIF_PROD FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO(COD_PRODUTO)
);
GO

CREATE TABLE MOVIMENTO_MANUAL (
    DAT_MES         INT           NOT NULL,
    DAT_ANO         INT           NOT NULL,
    NUM_LANCAMENTO  INT           NOT NULL,
    COD_PRODUTO     VARCHAR(11)   NOT NULL,
    COD_COSIF       VARCHAR(11)   NOT NULL,
    VAL_VALOR       DECIMAL(18,2) NOT NULL,
    DES_DESCRICAO   VARCHAR(50)   NOT NULL,
    DAT_MOVIMENTO   DATETIME2     NOT NULL,
    COD_USUARIO     VARCHAR(15)   NOT NULL,
    CONSTRAINT PK_MOVIMENTO_MANUAL PRIMARY KEY (DAT_MES, DAT_ANO, NUM_LANCAMENTO),
    CONSTRAINT FK_MM_PROD FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO(COD_PRODUTO),
    CONSTRAINT FK_MM_COSIF FOREIGN KEY (COD_PRODUTO, COD_COSIF) REFERENCES PRODUTO_COSIF(COD_PRODUTO, COD_COSIF)
);
GO

INSERT INTO PRODUTO (COD_PRODUTO, DES_PRODUTO, STA_STATUS) VALUES
('PROD01', 'Produto 1', 'A'),
('PROD02', 'Produto 2', 'A'),
('PROD03', 'Produto 3', 'A');

INSERT INTO PRODUTO_COSIF (COD_PRODUTO, COD_COSIF, COD_CLASSIFICACAO, STA_STATUS) VALUES
('PROD01', 'COS01', '0001', 'A'),
('PROD01', 'COS02', '0002', 'A'),
('PROD02', 'COS03', '0003', 'A'),
('PROD03', 'COS04', '0004', 'A');

INSERT INTO MOVIMENTO_MANUAL (DAT_MES, DAT_ANO, NUM_LANCAMENTO, COD_PRODUTO, COD_COSIF, VAL_VALOR, DES_DESCRICAO, DAT_MOVIMENTO, COD_USUARIO) VALUES
(8, 2025, 1, 'PROD01', 'COS01', 120.50, 'Lançamento inicial', SYSUTCDATETIME(), 'Rafael'),
(8, 2025, 2, 'PROD01', 'COS02', 90.00,  'Lançamento adicional', SYSUTCDATETIME(), 'Rodrigo'),
(8, 2025, 3, 'PROD02', 'COS03', 50.00,  'Material', SYSUTCDATETIME(), 'Jefferson');
